define([
    'jquery',
    'angular',
    'angularAnimate',
    'angularRoute',
    'angularBootstrap',
    'angularBootstrapTemplates',
    'angularResource',
    'services/validationServices',
    'services/spinnerServices',
    'common/header',
    'common/footer',
    'popups/contactMe',
    'popups/message',
    'pages/about',
    'pages/home',
    'pages/freeConsult',
    'pages/healthHistoryMen',
    'pages/healthHistoryWomen'
],
($, angular) => {
    angular.module('takeChargeHealth', 
        [
            'ngRoute',
            'ngAnimate',
            'ngResource',
            'ui.bootstrap',
            'ui.bootstrap.tpls',
            'header',
            'footer',
            'home',
            'about',
            'consult',
            'healthHistoryMen',
            'healthHistoryWomen',
            'contact',
            'message',
            'validation',
            'spinnerServices'
        ])
        .config(['$routeProvider', '$locationProvider', ($routeProvider, $locationProvider) => {
            $routeProvider.otherwise({redirectTo: '/'});
        }]);
});